// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7N9mpdEHP5TWnPx-S3tOwvdvFoBiJMBY',
    appId: '1:983841823918:web:f528660d9c2d84c546213f',
    messagingSenderId: '983841823918',
    projectId: 'e-therapy-f78d2',
    authDomain: 'e-therapy-f78d2.firebaseapp.com',
    storageBucket: 'e-therapy-f78d2.firebasestorage.app',
    measurementId: 'G-M9K72S5HGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy-It9mC6KLjaAShOjLYVV3ox3JFoazZ8',
    appId: '1:983841823918:android:02410ee79a5fa69246213f',
    messagingSenderId: '983841823918',
    projectId: 'e-therapy-f78d2',
    storageBucket: 'e-therapy-f78d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpJnYpRSHTUcC8psv8DAAeq2js6A7psP0',
    appId: '1:983841823918:ios:3a3a325c59512c5346213f',
    messagingSenderId: '983841823918',
    projectId: 'e-therapy-f78d2',
    storageBucket: 'e-therapy-f78d2.firebasestorage.app',
    iosBundleId: 'com.example.fypTherapy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpJnYpRSHTUcC8psv8DAAeq2js6A7psP0',
    appId: '1:983841823918:ios:3a3a325c59512c5346213f',
    messagingSenderId: '983841823918',
    projectId: 'e-therapy-f78d2',
    storageBucket: 'e-therapy-f78d2.firebasestorage.app',
    iosBundleId: 'com.example.fypTherapy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7N9mpdEHP5TWnPx-S3tOwvdvFoBiJMBY',
    appId: '1:983841823918:web:ceabb4181ef81a9446213f',
    messagingSenderId: '983841823918',
    projectId: 'e-therapy-f78d2',
    authDomain: 'e-therapy-f78d2.firebaseapp.com',
    storageBucket: 'e-therapy-f78d2.firebasestorage.app',
    measurementId: 'G-J3SLXMT7J3',
  );
}
